# localization.py

LANGUAGES = {
    "en": {
        "page_title": "AI Financial Inclusion Navigator",
        "page_icon": "🤖",
        "main_title": "AI Financial Inclusion Navigator",
        "caption": "Personalized AI agent to find government schemes and financial aid for you",
        "lang_select": "Select Language",
        "theme_toggle": "Light Mode",
        "sidebar_header": "👤 Complete Your Profile",
        "sidebar_subheader": "Fill in your details to get personalized scheme recommendations.",
        "basic_info": "Basic Information",
        "full_name": "Full Name",
        "age": "Age",
        "gender": "Gender",
        "male": "Male",
        "female": "Female",
        "other": "Other",
        "state": "State",
        "category": "Category",
        "economic_profile": "Economic Profile",
        "income": "Annual Family Income (₹)",
        "occupation": "Occupation",
        "find_schemes_button": "✨ Find My Schemes",
        "dashboard_tab": "My Dashboard",
        "chat_tab": "Chat with AI",
        "dashboard_header": "🌟 Your Personalized Scheme Dashboard",
        "dashboard_subheader": "Here are the top schemes we found. Hover over a card to see it in 3D!",
        "dashboard_info": "Please complete your profile in the sidebar and click 'Find My Schemes' to see your personalized recommendations.",
        "chat_header": "💬 Chat with our AI Assistant",
        "chat_subheader": "Ask follow-up questions, or use your voice to find new schemes.",
        "chat_input_prompt": "Type your message here...",
        "toast_schemes_found": "We've found the best schemes for your profile!",
        "toast_schemes_updated": "Schemes updated! Check the 'My Dashboard' tab.",
        "benefit": "Benefit",
        "match_score": "Match Score",
        "apply_now": "🚀 Apply Now",
        "call_helpline": "📞 Call Helpline",
        "explain_eligibility": "Why am I eligible?",
        "eligibility_explanation": "Based on your profile, you are a good match for **{scheme_name}** because it is designed for people who are: **{reasons}**.",
        "greeting_response": "Hello! I am your AI assistant. How can I help you today? You can tell me about your occupation or your needs.",
        "occupation_response": "Great, I understand you are a {occupation}. Based on this, I can find relevant schemes. Type 'show schemes' to see them.",
        "need_response": "Understood. You are looking for a {need}. Let me see what I can find. Type 'show schemes' to see your options.",
        "request_schemes_response": "I am calculating the best schemes for you based on our conversation. You can see them in the 'My Dashboard' tab.",
        "unknown_response": "I'm sorry, I didn't quite understand. You can tell me if you are a 'farmer', 'student', or need a 'business loan'.",
    },
    "hi": {
        "page_title": "एआई वित्तीय समावेशन नेविगेटर",
        "page_icon": "🤖",
        "main_title": "एआई वित्तीय समावेशन नेविगेटर",
        "caption": "आपके लिए सरकारी योजनाओं और वित्तीय सहायता को खोजने वाला व्यक्तिगत एआई एजेंट",
        "lang_select": "भाषा चुनें",
        "theme_toggle": "लाइट मोड",
        "sidebar_header": "👤 अपनी प्रोफाइल पूरी करें",
        "sidebar_subheader": "व्यक्तिगत योजना अनुशंसाएं प्राप्त करने के लिए अपना विवरण भरें।",
        "basic_info": "बुनियादी जानकारी",
        "full_name": "पूरा नाम",
        "age": "आयु",
        "gender": "लिंग",
        "male": "पुरुष",
        "female": "महिला",
        "other": "अन्य",
        "state": "राज्य",
        "category": "श्रेणी",
        "economic_profile": "आर्थिक प्रोफ़ाइल",
        "income": "वार्षिक पारिवारिक आय (₹)",
        "occupation": "व्यवसाय",
        "find_schemes_button": "✨ मेरी योजनाएं खोजें",
        "dashboard_tab": "मेरा डैशबोर्ड",
        "chat_tab": "एआई से चैट करें",
        "dashboard_header": "🌟 आपका व्यक्तिगत योजना डैशबोर्ड",
        "dashboard_subheader": "यहां वे शीर्ष योजनाएं हैं जो हमें मिलीं। 3डी में देखने के लिए कार्ड पर होवर करें!",
        "dashboard_info": "कृपया अपनी व्यक्तिगत सिफारिशों को देखने के लिए साइडबार में अपनी प्रोफ़ाइल पूरी करें और 'मेरी योजनाएं खोजें' पर क्लिक करें।",
        "chat_header": "💬 हमारे एआई सहायक के साथ चैट करें",
        "chat_subheader": "अनुवर्ती प्रश्न पूछें, या नई योजनाएं खोजने के लिए अपनी आवाज का उपयोग करें।",
        "chat_input_prompt": "अपना संदेश यहां टाइप करें...",
        "toast_schemes_found": "हमें आपकी प्रोफ़ाइल के लिए सबसे अच्छी योजनाएँ मिल गई हैं!",
        "toast_schemes_updated": "योजनाएं अपडेट की गईं! 'मेरा डैशबोर्ड' टैब देखें।",
        "benefit": "लाभ",
        "match_score": "मिलान स्कोर",
        "apply_now": "🚀 अभी आवेदन करें",
        "call_helpline": "📞 हेल्पलाइन पर कॉल करें",
        "explain_eligibility": "मैं पात्र क्यों हूं?",
        "eligibility_explanation": "आपकी प्रोफ़ाइल के आधार पर, आप **{scheme_name}** के लिए एक अच्छे मेल हैं क्योंकि यह उन लोगों के लिए डिज़ाइन किया गया है जो हैं: **{reasons}**।",
        "greeting_response": "नमस्ते! मैं आपका एआई सहायक हूं। मैं आज आपकी कैसे मदद कर सकता हूं? आप मुझे अपने व्यवसाय या अपनी जरूरतों के बारे में बता सकते हैं।",
        "occupation_response": "बहुत अच्छा, मैं समझ गया कि आप एक {occupation} हैं। इसके आधार पर, मैं आपके लिए प्रासंगिक योजनाएं ढूंढ सकता हूं। उन्हें देखने के लिए 'योजनाएं दिखाएं' टाइप करें।",
        "need_response": "समझ गया। आप एक {need} की तलाश में हैं। मुझे देखने दीजिए कि मैं क्या ढूंढ सकता हूं। अपने विकल्प देखने के लिए 'योजनाएं दिखाएं' टाइप करें।",
        "request_schemes_response": "मैं हमारी बातचीत के आधार पर आपके लिए सबसे अच्छी योजनाओं की गणना कर रहा हूं। आप उन्हें 'मेरी योजनाएं' टैब में देख सकते हैं।",
        "unknown_response": "मुझे क्षमा करें, मैं पूरी तरह से समझ नहीं पाया। आप मुझे बता सकते हैं कि क्या आप 'किसान', 'छात्र' हैं, या 'व्यापार ऋण' की आवश्यकता है।",
    }
}